### ISSUE TITLE
Add commit hash to dictionary repo URLs

### ISSUE THREAD

**Issue by vipranarayan14** [indic-dict/stardict-index#1]
I am using this to [build a dict installer](https://groups.google.com/g/sanskrit-programmers/c/RLKbviRQBOU/m/oVPXEEkjCAAJ).

Can you add commit hash to the dictionary repo URLs listed in 'dictionaryIndices.md` file?

I need this because the list of dicts that I maintain locally goes out of sync everytime the URL of dictionary archive (tar.gz) changes. 

Adding hash will ensure that the list I maintain always points to valid URLs of dict archives (even if there are old).

**Comment by vvasuki** [comment]
Dictionary repo urls don't usually change. dictionary urls change often. I suppose you mean the latter. If so:

This will complicate the currently (semi)automated dictionary publishing process (I'd need to update hashes everytime a dict is committed!) So, don't want to do this.  
Besides, it's not ideal to point to outdated dicts.

My suggestion is  - don't maintain an offline list (at least of the urls) - get them fresh each time .
